### ISSUE TITLE
NameError: name 'char_field' is not defined

### ISSUE THREAD

**Issue by susht3** [schelotto/Neural_Speed_Reading_via_Skim-RNN_PyTorch#2]
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    train_iter, test_iter = load_data(text_field, label_field, device=-1, repeat=False)
  File "main.py", line 47, in load_data
    train_data, test_data = dataset.splits(text_field, label_field)
  File "/data/Neural_Speed_Reading_via_Skim-RNN_PyTorch/dataset.py", line 101, in splits
    examples = cls(text_field, char_field, label_field, path=path, **kwargs).examples
NameError: name 'char_field' is not defined

**Comment by schelotto** [comment]
The bug is fixed. Thanks.
